backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

publish_mode: editorial_workflow

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - file: "content/site.json"
        label: "Site Content"
        name: "site"
        fields:
          - { label: "Welcome Text", name: "welcome", widget: "string" }
          - { label: "Header Description", name: "headerDescription", widget: "string" }
          - { label: "Typing Text List", name: "typing", widget: "list", field: {label: Text, name: text, widget: string} }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Audio Title", name: "audioTitle", widget: "string", default: "Ikigai.mp3" }

  - name: "services"
    label: "Services"
    file: "content/services.json"
    fields:
      - label: "Services"
        name: "items"
        widget: "list"
        fields:
          - {label: "Icon (FontAwesome class)", name: "icon", widget: "string", default: "fa-solid fa-code"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}

  - name: "works"
    label: "Works"
    label_singular: "Work"
    folder: "content/works"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - {label: "ID (URL param)", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Short Excerpt", name: "excerpt", widget: "text"}
      - {label: "Description", name: "description", widget: "text"}
      - label: "Features"
        name: "features"
        widget: "list"
        field: {label: "Feature", name: "feature", widget: "string"}
      - {label: "Live Demo URL", name: "liveDemo", widget: "string", required: false}
      - {label: "Source Code URL", name: "sourceCode", widget: "string", required: false}
