backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - file: "content/site.json"
        label: "Site Content"
        name: "site"
        fields:
          - { label: "Welcome Text", name: "welcome", widget: "string" }
          - { label: "Header Description", name: "headerDescription", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
